//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_inferno_2x2.html
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
overviews/de_inferno_2x2.txt
overviews/de_inferno_2x2.bmp
maps/de_inferno_2x2.bsp
maps/de_inferno_2x2.txt
