//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_oc2.html
overviews/de_oc2.txt
gfx/env/sp_zavod_bk.tga
gfx/env/sp_zavod_dn.tga
gfx/env/sp_zavod_ft.tga
gfx/env/sp_zavod_lf.tga
gfx/env/sp_zavod_rt.tga
gfx/env/sp_zavod_up.tga
maps/de_oc2.bsp
