//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_piranesi.html
halflife.wad
decals.wad
sound/ambience/sheep.wav
sound/ambience/cow.wav
sound/ambience/crow.wav
sprites/glow01.spr
models/pi_fern.mdl
models/pi_tree.mdl
models/pi_treeb.mdl
models/pi_shrub.mdl
models/pi_stlamp.mdl
models/pi_outlamp1.mdl
sound/ambience/sparrow.wav
sound/ambience/3dmeagle.wav
sound/ambience/birds6.wav
sound/ambience/birds4.wav
sound/ambience/birds9.wav
sound/ambience/dog1.wav
sound/ambience/dog2.wav
sound/ambience/dog3.wav
sound/ambience/dog4.wav
sound/ambience/dog5.wav
sound/ambience/waterrun.wav
sound/ambience/car1.wav
sound/ambience/car2.wav
sound/ambience/tankidle2.wav
de_piranesi.wad
gfx/env/cxbk.tga
gfx/env/cxdn.tga
gfx/env/cxft.tga
gfx/env/cxlf.tga
gfx/env/cxrt.tga
gfx/env/cxup.tga
maps/de_piranesi.bsp
