//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_russia_2x2.html
halflife.wad
decals.wad
liquids.wad
spraypaint.wad
cs_cbble.wad
cstrike.wad
cs_dust.wad
cs_assault.wad
de_aztec.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
torntextures.wad
ajawad.wad
tswad.wad
cached.wad
cstraining.wad
maps/de_russia_2x2.bsp
