//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_vertigo.html
halflife.wad
decals.wad
sound/ambience/wind2.wav
cstrike.wad
de_vertigo.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
sound/ambience/fallscream.wav
sprites/flare2.spr
overviews/de_vertigo.txt
overviews/de_vertigo.bmp
maps/de_vertigo.bsp
maps/de_vertigo.txt
